// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWwwY7yOv0RppAVBGtL1IjhXI5Revls_U',
    appId: '1:1008882272315:web:246eed14fb6940ed55f41e',
    messagingSenderId: '1008882272315',
    projectId: 'quiz-app-a04a3',
    authDomain: 'quiz-app-a04a3.firebaseapp.com',
    databaseURL: 'https://quiz-app-a04a3-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-a04a3.appspot.com',
    measurementId: 'G-NHJXR32YRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjjr3ZV0DdMw0OSDbKyO-VtMpluUKyAlo',
    appId: '1:1008882272315:android:5c5cf2b3b60e86be55f41e',
    messagingSenderId: '1008882272315',
    projectId: 'quiz-app-a04a3',
    databaseURL: 'https://quiz-app-a04a3-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-a04a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiWEm6-Sb46OLg3v__Ccxy3EgainHrxPQ',
    appId: '1:1008882272315:ios:3ecef24f81e0068b55f41e',
    messagingSenderId: '1008882272315',
    projectId: 'quiz-app-a04a3',
    databaseURL: 'https://quiz-app-a04a3-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-a04a3.appspot.com',
    iosBundleId: 'com.example.prolifeService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiWEm6-Sb46OLg3v__Ccxy3EgainHrxPQ',
    appId: '1:1008882272315:ios:3ecef24f81e0068b55f41e',
    messagingSenderId: '1008882272315',
    projectId: 'quiz-app-a04a3',
    databaseURL: 'https://quiz-app-a04a3-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-a04a3.appspot.com',
    iosBundleId: 'com.example.prolifeService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWwwY7yOv0RppAVBGtL1IjhXI5Revls_U',
    appId: '1:1008882272315:web:06e9e16a349d038855f41e',
    messagingSenderId: '1008882272315',
    projectId: 'quiz-app-a04a3',
    authDomain: 'quiz-app-a04a3.firebaseapp.com',
    databaseURL: 'https://quiz-app-a04a3-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-a04a3.appspot.com',
    measurementId: 'G-8YQRXPQEYH',
  );
}
