// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPLlj8Bp0SDf0CVuJx2qeGP63pFqWH7VI',
    appId: '1:346719973558:web:e5743405286c49e6557617',
    messagingSenderId: '346719973558',
    projectId: 'storeimage-40b3d',
    authDomain: 'storeimage-40b3d.firebaseapp.com',
    databaseURL: 'https://storeimage-40b3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'storeimage-40b3d.appspot.com',
    measurementId: 'G-19Y66QH1VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtQIKpLlKK2IqiAvNASs-lkDXSIVfZJa0',
    appId: '1:346719973558:android:65bc4d1a22bf5359557617',
    messagingSenderId: '346719973558',
    projectId: 'storeimage-40b3d',
    databaseURL: 'https://storeimage-40b3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'storeimage-40b3d.appspot.com',
  );
}
