// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh-Pk91R3E3T0ZgJmHTuAWFjlENcA-aKw',
    appId: '1:842818888924:web:181665b7a3e8482d994019',
    messagingSenderId: '842818888924',
    projectId: 'image-uplode-4d545',
    authDomain: 'image-uplode-4d545.firebaseapp.com',
    databaseURL: 'https://image-uplode-4d545-default-rtdb.firebaseio.com',
    storageBucket: 'image-uplode-4d545.appspot.com',
    measurementId: 'G-ZSD7V7GCEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdw_P4E2uOPxIDEaAGxsXEd0qTa41CMwY',
    appId: '1:842818888924:android:56a1f00aead4c86e994019',
    messagingSenderId: '842818888924',
    projectId: 'image-uplode-4d545',
    databaseURL: 'https://image-uplode-4d545-default-rtdb.firebaseio.com',
    storageBucket: 'image-uplode-4d545.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYEc_NM7EiOv3YqzP3abl3GqesCPdkRgc',
    appId: '1:842818888924:ios:afea128052e1e39b994019',
    messagingSenderId: '842818888924',
    projectId: 'image-uplode-4d545',
    databaseURL: 'https://image-uplode-4d545-default-rtdb.firebaseio.com',
    storageBucket: 'image-uplode-4d545.appspot.com',
    iosBundleId: 'com.example.prolifeService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYEc_NM7EiOv3YqzP3abl3GqesCPdkRgc',
    appId: '1:842818888924:ios:afea128052e1e39b994019',
    messagingSenderId: '842818888924',
    projectId: 'image-uplode-4d545',
    databaseURL: 'https://image-uplode-4d545-default-rtdb.firebaseio.com',
    storageBucket: 'image-uplode-4d545.appspot.com',
    iosBundleId: 'com.example.prolifeService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh-Pk91R3E3T0ZgJmHTuAWFjlENcA-aKw',
    appId: '1:842818888924:web:e497dc0defc158ab994019',
    messagingSenderId: '842818888924',
    projectId: 'image-uplode-4d545',
    authDomain: 'image-uplode-4d545.firebaseapp.com',
    databaseURL: 'https://image-uplode-4d545-default-rtdb.firebaseio.com',
    storageBucket: 'image-uplode-4d545.appspot.com',
    measurementId: 'G-9FNLG3YXQ2',
  );
}